---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-plus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-plus
  template:
    metadata:
      labels:
        app: nginx-plus
    spec:
      containers:
      - name: nginx-plus
        image: registry.example.com/nginx-plus:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-plus-svc
  labels:
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx-plus
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: nginx-plus-webapp
spec:
  host: webapp.example.com
  upstreams:
  - name: nginx-plus
    service: nginx-plus-svc
    port: 80
  routes:
  - path: /
    action:
      pass: nginx-plus