version: '3'
services:
    httpbin-app:
        image: kennethreitz/httpbin
        environment:
            - "GUNICORN_CMD_ARGS=\"--capture-output --error-logfile - --access-logfile - --access-logformat \"%(h)s %(t)s %(r)s %(s)s Host: %({Host}i)s}\"\""
        expose:
         - "80"
    nginx-lb:
        image: agent-plus:latest
        hostname: agent-plus
        ports:
        - "8080:80"
        environment:
         - NMS_HOST=10.1.1.5
         - NMS_GRPC_PORT=443
    nginx-gw:
        image: agent-plus-napw:latest
        hostname: agent-plus-napw
        ports:
        - "8081:80"
        environment:
         - NMS_HOST=10.1.1.5
         - NMS_GRPC_PORT=443
         - NMS_INSTANCEGROUP=napw-cluster
         - NMS_TAG=napw-proxy
    nginx-gw2:
        image: plus:latest
        hostname: plus
        ports:
        - "8081:80"

